name: Deploy with Ansible

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python and Ansible
        run: |
          python -m pip install --upgrade pip
          pip install ansible azure-cli

      - name: Run provisioning playbook
        run: ansible-playbook ansible/playbooks/provision.yml -i ansible/inventories/staging/hosts.yml

      - name: Run deployment playbook
        run: ansible-playbook ansible/playbooks/deploy.yml -i ansible/inventories/staging/hosts.yml

      - name: Run post-deployment validation
        run: ansible-playbook ansible/playbooks/validate.yml -i ansible/inventories/staging/hosts.yml
